services:
  app:
    container_name: jdbc-playground
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOSTNAME: jdbc-playground-db
    network_mode: service:db
  db:
    container_name: jdbc-playground-db
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}